theme: jekyll-theme-cayman
title: Evolución COVID-19 en Galicia
description: Los datos que se presentan en esta página web se actualizan automáticamente todos los días a partir de la página web del SERGAS a las 11 AM. No obstante, contienen la actualización de los datos hecha a las 18 PM del día anterior. También puedes obtener información en el bot de Telegram @covid19_galicia_bot.


